spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: 1740

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080